# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BGRBVZwSyomlnr_S6522f-XIGVR5gwil
"""

medias = [6.0, 5.3, 8.2]

# Ordena da maior para a menor
ranking = sorted(medias, reverse=True)

# Mostra classificação
for posicao, media in enumerate(ranking, start=1):
    print(f"{posicao}º lugar - Média: {media}")

print("\nO maior CR tem a maior nota, matrícula 199214083.")